#! /bin/bash
#
# Install Thompson UDP listener service and timer
#
# June-2023, Pat Welch, pat@mousebrains.com

myPath=`dirname $0`

	# --service=udpProcess.service \

$myPath/TPWUtils/install.py \
	--verbose \
	--service=scs2NC.service \
	$*
