#! /usr/bin/bash -x

cmd="rsync --archive --verbose --delete --delete-excluded"
tgt=/home/pat/Sync/Ship

$cmd --exclude='._*' /thompson/share/Data/VMP $tgt
$cmd --exclude='._*' /thompson/share/Data/ship/ship*.nc $tgt/ship
$cmd --exclude='._*' /thompson/cruise/adcp/proc $tgt/adcp
$cmd --exclude='._*' /thompson/cruise/Glider $tgt
$cmd --exclude='._*' /thompson/cruise/uCTD $tgt
